config/routes.rb
Rails.application.routes.draw do
  
  get 'searches/new'

  get 'searches/result'


  resources :reservations
  resources :flights
  resources :airplanes
  root :to => 'session#new'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
  
  get '/users/edit' => 'users#edit', :as => :edit_user
  resources :users, :except => [:edit]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  name            :string
#  surname         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :text
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
	has_secure_password
	has_many :reservations
	has_many :flights, :through => :reservations

	validates :email, :presence => true, :uniqueness => true

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_if_logged_in, :only => [:show, :edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_if_admin, :only => [:index]



  # GET /users
  # GET /users.json
  def index
    @users = User.all
    unless @current_user.present? && @current_user.admin?
      redirect_to root_path
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find params[:id]
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = @current_user
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :name, :surname, :password, :password_confirmation)
    end

    def check_if_logged_in
      redirect_to root_path unless @current_user.present?
    end

    def check_if_admin
      redirect_to root_path unless @current_user.present? && @current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-4"></div>
    <div class="form-group col-md-4">
      <%= f.label :email, :class => 'sr-only', :for => 'exampleInputEmail3' %>
      <%= f.email_field :email, :class => 'form-control', :id => 'exampleInputEmail3', :placeholder => 'Email' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="form-group col-md-4">
      <%= f.label :name, :class => 'sr-only', :for => 'exampleInputName3' %>
      <%= f.text_field :name, :class => 'form-control', :id => 'exampleInputName3', :placeholder => 'Name' %>
    </div>
  </div>  
  <div class="row">
    <div class="col-md-4"></div>
    <div class="form-group col-md-4">
      <%= f.label :surname, :class => 'sr-only', :for => 'exampleInputSurname3' %>
      <%= f.text_field :surname, :class => 'form-control', :id => 'exampleInputSurname3', :placeholder => 'Surname' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="form-group col-md-4">
      <%= f.label :password, :class => 'sr-only', :for => 'exampleInputPassword3' %>
      <%= f.password_field :password, :class => 'form-control', :id => 'exampleInputPassword3', :placeholder => 'Password' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="form-group col-md-4">
      <%= f.label :password_confirmation, :class => 'sr-only', :for => 'exampleInputPassword3' %>
      <%= f.password_field :password_confirmation, :class => 'form-control', :id => 'exampleInputPassword3', :placeholder => 'Confrim Password' %>
    </div>
  </div>


  <div class="row">
    <div class="col-md-4"></div>
    <%= submit_tag "Submit", :class => 'btn btn-default submit' %>
  </div>
  
  <% end %>

  <p>Already have an account? Go back to the <%= link_to 'Login', login_path%> Page</p>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Surname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 	<strong>Email:</strong>
  	<%= @user.email %>
</p>

<p>
  	<strong>Name:</strong>
  	<%= @user.name %>
</p>

<p>
  	<strong>Surname:</strong>
  	<%= @user.surname %>
</p>


<% @user.reservations.each do |reservation| %>
<ul>
	<li>
		<%= reservation.flight.flight_number %>
	</li>
	<li>
		Seat: <%= reservation.row %><%= reservation.column %>
	</li>
	<li>
		<%= reservation.flight.date %>
	</li>
</ul>
<% end %>


<%= link_to 'Edit', edit_user_path(@user) %>